### ISSUE TITLE
Mehrfachzählung, wenn FE Modul in mehreren Layouts eingebunden wird

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/visitors#187]
[Forum](https://community.contao.org/de/showthread.php?58588-Visitors-z%E4hlt-nach-Update-zuviel)

Besucher Anzahl erhöht sich.

**Comment by KlausGrenoble** [comment]
Hat das vielleicht mit dem Cache zu tun ?
"Damit kann auch gezählt werden, wenn die Seite im Browsercache liegt und daraus aufgerufen wird.
Die System Einstellung "Cache-Modus" wird dabei beachtet."

**Comment by BugBuster1701** [comment]
Kann ich nicht nachvollziehen.
