### ISSUE TITLE
PHP 7.1 Problem?!

### ISSUE THREAD

**Issue by kozi** [BugBuster1701/visitors#215]
Sobald ich ein definiertes Modul `Besucherzähler` einbinde lädt die gesamte Seite nicht mehr!
![sobald](https://cloud.githubusercontent.com/assets/464029/23673570/11d3b524-0373-11e7-81a0-b5faecfdf2a5.png)

Contao: 3.5.24
bugbuster/visitors: 3.8.1
PHP: 7.1.2

Würde gerne eine bessere Fehlermeldung liefern. Bekomme aber nichts angezeigt. Irgendeine Idee?

**Comment by kozi** [comment]
Wenn ich die PHP Version auf **7.0.15** umstelle tritt der Fehler nicht mehr auf und die Seite lässt sich ohne Probleme laden

**Comment by BugBuster1701** [comment]
Nichts in system/logs/error.log?

**Comment by kozi** [comment]
Leider nein!

**Comment by kozi** [comment]
Habe jetzt auch noch mal auf einer anderen Installation getestet. Der Fehler tritt definitiv im Zusammtenhang von PHP 7.1 auf. Mit PHP 7.0 ist alles in Ordnung.

**Comment by BugBuster1701** [comment]
Kann ich nicht nachvollziehen. Gerade frisch installiert Ubuntu 16.10, php 7.1.2, Contao 3.5.24 und Visitors 3.8.1 (mit botdetection 4.2.0 Build 11)

**Comment by BugBuster1701** [comment]
Falls nicht bereits so eingestellt im Backend, die Fehlermeldungen einschalten ("Fehlermeldungen protokollieren") und anzeigen lassen ("Fehlermeldungen anzeigen")

**Comment by kozi** [comment]
Danke für die Info. Werde mal versuchen den Fehler einzugrenzen und meld mich dann noch mal.

**Comment by kozi** [comment]
Ich habe jetzt unter eine Subdomain noch einmal eine aktuelle Contao Version 3.5.24 installiert.
Habe dann nur die visitors Erweiterung über Composer installiert.
Dann habe ich eine minimal Konfiguration vorgenommen (Kategorie mit einem Zähler und dazu ein Besucher-Modul). Das Modul habe ich dann im Layout eingebunden. 

Der verwendete Webspace liegt bei **1und1**.

In die error.log wird nichts geschrieben und als Ausgabe im Browser bekomme ich auch nur den Inhalt wie auf dem Screenshot zu sehen.


Mit `PHP 7.0.16`:
![unbenannt04](https://cloud.githubusercontent.com/assets/464029/23740610/a9c460f4-04a4-11e7-9493-561d8ea93497.PNG)

Aktiviere ich dann `PHP 7.1.2`
![unbenannt03](https://cloud.githubusercontent.com/assets/464029/23740632/c49a2a80-04a4-11e7-8d6b-f2cd2ecfa63c.PNG)

Details:

![unbenannt02](https://cloud.githubusercontent.com/assets/464029/23740641/d002fbae-04a4-11e7-911a-75c415572ac6.PNG)
![unbenannt01](https://cloud.githubusercontent.com/assets/464029/23740644/d2efd47c-04a4-11e7-90cb-c25300e93c51.PNG)

**Comment by BugBuster1701** [comment]
Schon mal den Contao Check unter 7.1.2 laufen lassen? Nur zur Sicherheit, denn ich entdecke so erst mal nichts auffälliges.
Falls möglich mal in die Error Log vom Webserver schauen ob dort Fehlermeldungen auftauchen.

**Comment by kozi** [comment]
![unbenann1t](https://cloud.githubusercontent.com/assets/464029/23751723/d5c420c6-04d2-11e7-9195-5af19e857f7f.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/464029/23751739/e69759c2-04d2-11e7-9c47-d222cb8dde12.PNG)

**Comment by kozi** [comment]
Es wird leider nirgendwo ein Fehler ausgegeben...

Auch wenn ich über eine `php.ini` die error logs aktiviere. hilfe-center.1und1.de/hosting/1und1-webhosting-c10085285/skript--und-programmiersprachen-c10082634/php-c10082686/problemloesung-c10085144/error-logs-aktivieren-a10790768.html

**Comment by BugBuster1701** [comment]
Also jetzt habe ich mal, das ging am Anfang nicht, auch auf Composer umgestellt.
Jetzt habe ich dasselbe Problem. Allerdings sehe ich Meldungen in der error.log vom Apache, der stürzt mit einem Core Dump ab. Heftig. Da muss irgendwas das PHP Modul zum Absturz bringen, schätze ich mal.
Da Visitors un Botdetection über Composer identisch ist mit der vom ER2 kann das nur an einer Abhängigkeit liegen die Botdetection über ER2 mitbringt und über Composer direkt aus Github zieht.
Mal sehen ob ich das aufgedröselt bekomme.

**Comment by BugBuster1701** [comment]
PS: Ich hoffe mal das liegt nicht an meinem PHP 7.1 was über externe Quelle parallel zu 7.0 installiert ist.

**Comment by BugBuster1701** [comment]
Browscap 1.x Abhängigkeit zu alt, Aufruf des Parsers in der Datei Browscap.php Zeile 135 
```
        // try to get browser data
        $return = static::getParser()->getBrowser($user_agent);
```
führt zu Fehler.
Version 2.x ist ab PHP 5.6, benötigt aber pdo_sqlite oder sqlite3 Extension.
Test nötig.

**Comment by BugBuster1701** [comment]
Ist ein Problem von meiner Erweiterung Botdetection bzw. wird darin behoben.
Siehe BugBuster1701/botdetection/issues/148

**Comment by BugBuster1701** [comment]
Neue Version Botdetection 4.2.1 (für Composer / Paketverwaltung) ist veröffentlicht.

**Comment by kozi** [comment]
DANKE!
