### ISSUE TITLE
Zählung überspringen bei HEAD Request

### ISSUE THREAD

**Issue by KaiserCh** [BugBuster1701/visitors#216]
Aktuell ist es so, dass auch reine HEAD Requests vom Besucherzähler erfasst werden. Das ist in soweit problematisch, dass so ein HEAD Request ja kein echter Besuch ist sondern schlichtweg die Statistik verfälscht.
Erschwerend kommt hinzu, dass wir bei einem unserer Kunden gerade den interessanten Fall haben, dass die Visitors-Liste rappelvoll mit russischen und ukrainischen Domains (z.B. Sexshops) als Referer ist. Laut Apache-Log sind das aber alles nur HEAD Requests mit nem absolut minimalistischen aber plausiblen User Agent (Mozilla Compatible blabla).

Es wäre ganz nett, wenn z.B. über $_SERVER['REQUEST_METHOD'] geprüft würde, ob der Request auch wirklich ein GET oder evtl. POST war. Die anderen Methoden wie PATCH, PUT, HEAD, OPTION,... spielen für einen Besucherzähler ja eigentlich keine Rolle.

**Comment by BugBuster1701** [comment]
An die Liste mit den Referrer Spam Adressen hätte ich Interesse, da Visitors auch solche versucht zu erkennen (über Drittanbieter und eigene Kennungen)

**Comment by KaiserCh** [comment]
Klar, zumindest die auffälligen Adressen, die in den Top30 erscheinen, kann ich dir gern geben. 
Ich schick dir die Liste über das Kontaktformular auf contao.ninja, wir müssen den Spammern ja hier nicht auch noch ne Plattform bieten.

**Comment by BugBuster1701** [comment]
OK, Danke.

**Comment by BugBuster1701** [comment]
Botdetection angepasst, es werden nur noch GET und POST Zugriffe gezählt.
