### ISSUE TITLE
Backend Besucherstatistik - Rücksetzung für bestimmte Benutzergruppen verbieten

### ISSUE THREAD

**Issue by Schmidty2** [BugBuster1701/visitors#224]
Hallo,
kann eine Option hinzugefügt werden, damit die Rücksetzfunktion im Menüpunkt Besucherstatistik für bestimmte Benutzergruppen ausgeblendet werden kann.
Ich hatte jetzt schon zwei Mal den Fall, dass ein Redakteur, der zwar die Besucherzahlen einsehen darf, die Statistik zurückgesetzt hat (Das was man an Menüpunkten angeboten bekommt - wird auch verwendet).
![grafik](https://user-images.githubusercontent.com/2067428/42418457-23ce4448-82a1-11e8-9635-8bd38c7e0c97.png)
Danke.

**Comment by BugBuster1701** [comment]
- [ ] Einstellung in der Kategorie
- [ ] Abfrage der Erlaubnis in der Statistik
- [ ] Anpassung des Templates (Ein-/Ausblenden)
- [ ] setZero Anpassung, Erlaubnis prüfen

**Comment by BugBuster1701** [comment]
Umsetzung erfolgt in der Contao 4 Version
https://github.com/BugBuster1701/contao-visitors-bundle/issues/39
