### ISSUE TITLE
Undefnierte Konstante BE_USER_LOGGED_IN

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/visitors#229]
Kommt von hier: https://github.com/contao/core/blob/3.5/system/modules/core/models/PageModel.php#L515
Meldung im [Forum](https://community.contao.org/de/showthread.php?73874-Visitor-mit-Fehler-in-der-error-log&p=495077&viewfull=1#post495077)

**Comment by fritzmg** [comment]
Ich würde einfach ein
```php
if (!defined('BE_USER_LOGGED_IN')) {
    define('BE_USER_LOGGED_IN', false);
}
```
für den Insert Tag einbauen. Evt. das selbe auch für FE_USER_LOGGED_IN. 

An anderen Stellen in Contao werden diese Konstanten auch einfach auf false gesetzt.
